### ISSUE TITLE
win10 启动 server_v1.0.7.exe 异常

### ISSUE THREAD

**Issue by cybexr** [592767809/video_server#34]
Traceback (most recent call last):
  File "server.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\root_context.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\protocol\__init__.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\protocol\http.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\http.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\request.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\message.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\encoding.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "brotli.py", line 8, in <module>
ImportError: DLL load failed while importing _brotli: 找不到指定的模块。

**Comment by 592767809** [comment]
尝试从 https://learn.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170 下载并安装对应系统版本的vc_redist

**Comment by cybexr** [comment]
好了 谢谢
