### ISSUE TITLE
在windows 11 下启动失败

### ISSUE THREAD

**Issue by Abeperspiration** [592767809/video_server#40]
主程序启动 弹窗提示：

Unhandled exception in script
Failed to execute script 'server' due to unhandled exception: DLL load failed while importing _brotli: 找不到指定的模块
Traceback (most recent call last):
  File "server.py", line 26, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\root_context.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\protocol\__init__.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\proxy\protocol\http.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\http.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\request.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\message.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "mitmproxy\net\http\encoding.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "brotli.py", line 8, in <module>
ImportError: DLL load failed while importing _brotli: 找不到指定的模块。

证书目录也没有生成对应的文件
微信已推出 缓存已删除 未开启代理

系统为windows 11 PVE虚拟机

**Comment by 592767809** [comment]
https://github.com/592767809/video_server/issues/34
